services:
  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.2
    container_name: zot
    restart: always
    ports:
      - "5000:5000"
    deploy:
        resources:
            limits:
              cpus: "1"
              memory: 1500m
            reservations:
              cpus: "0.5"
              memory: 1024m
